framework:
    rate_limiter:
        auth_requests:
            policy: sliding_window
            limit: 30
            interval: '15 minutes'
            cache_pool: cache.auth_limits
            lock_factory: app.auth_lock_factory
        password_reset:
            policy: sliding_window
            limit: 3
            interval: '15 minutes'
            cache_pool: cache.auth_limits
            lock_factory: app.auth_lock_factory
        justification_requests:
            policy: sliding_window
            limit: 60
            interval: '15 minutes'
            cache_pool: cache.auth_limits
            lock_factory: app.auth_lock_factory
        justification_upload:
            policy: sliding_window
            limit: 10
            interval: '15 minutes'
            cache_pool: cache.auth_limits
            lock_factory: app.auth_lock_factory
